export const SET_BUDGET = 'SET_BUDGET'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const HANDLE_TITLE = 'HANDLE_TITLE'
export const HANDLE_PRICE = 'HANDLE_PRICE'
export const SAVE_TEMPORARILY = 'SAVE_TEMPORARILY'
export const LOAD_SAVED = 'LOAD_SAVED'
